modLoader="javafml" 

loaderVersion="[36,)"

license="MIT"

[[mods]] 

modId="moreglasses"

version="1.16.5-1.0.0"

displayName="More Glasses"

logoFile="moreglasses.png"

credits="Nobody"

authors="Nobody" 

description='''
A mod that adds more glass blocks to minecraft.

that's it.

no, seriously that is it.

Mod by Nobody.

Submit any issues you have here:
https://github.com/NobodyCentral/MoreGlasses/issues
'''

[[dependencies.moreglasses]] #optional
    
    modId="forge" 
    
    mandatory=true 
    
    versionRange="[36,)" 
    
    ordering="NONE"
    
    side="BOTH"

[[dependencies.tubes]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
